name: dialer-app
version: 0.1+17.04.20161209-0ubuntu1
summary: Dialer application for Ubuntu
description: Dialer application for Ubuntu
confinement: devmode  # use "strict" to enforce system access only via declared interfaces
grade: devel

apps:
    dialer-app:
        command: desktop-launch $SNAP/usr/bin/dialer-app "$@"
        plugs: [opengl, platform, unity7, unity8, mir]

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target: ubuntu-app-platform
        default-provider: ubuntu-app-platform

parts:
    dialer-app:
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
        source: .
        build-packages:
            - cmake
            - intltool
            - pkg-config
            - qt5-default
            - qtbase5-dev
            - qtdeclarative5-dev
            - qtdeclarative5-dev-tools

        stage-packages:
            - qtdeclarative5-ubuntu-addressbook0.1
            - qtdeclarative5-ubuntu-history0.1
            - qtdeclarative5-ubuntu-telephony0.1
            - qtdeclarative5-ubuntu-telephony-phonenumber0.1

        snap:
            # dialer-app
            - usr/share/applications/dialer-app*.desktop
            - usr/share/url-dispatcher/urls
            - usr/share/locale/*/LC_MESSAGES/dialer-app.mo
            - usr/share/dialer-app/*.qml
            - usr/share/dialer-app/LiveCallPage
            - usr/share/dialer-app/HistoryPage
            - usr/share/dialer-app/DialerPage
            - usr/share/dialer-app/ContactsPage
            - usr/share/dialer-app/ContactViewPage
            - usr/share/dialer-app/ContactEditorPage
            - usr/share/dialer-app/Dialogs
            - usr/share/dialer-app/assets
            - usr/share/dialer-app/MMI
            - usr/bin/*dialer-app*       

            # qtdeclarative5-ubuntu-addressbook0.1
            - usr/lib/*/qt5/qml/Ubuntu/Contacts.0.1/
            - usr/share/doc/qtdeclarative5-ubuntu-contacts0.1/copyright
            - usr/lib/*/qt5/qml/Ubuntu/AddressBook/
            - usr/share/doc/qtdeclarative5-ubuntu-addressbook0.1/copyright

            # qtdeclarative5-ubuntu-history0.1
            - usr/share/doc/qtdeclarative5-ubuntu-history0.1/copyright
            - usr/lib/*/qt5/qml/Ubuntu/History/libhistory-qml.so
            - usr/lib/*/qt5/qml/Ubuntu/History/qmldir
            - usr/lib/*/libhistoryservice.so.*
            - usr/lib/*/libtelepathy-qt5.so.*

            # qtdeclarative5-ubuntu-telephony0.1
            - usr/lib/*/qt5/qml/Ubuntu/Telephony/
            - usr/share/doc/qtdeclarative5-ubuntu-telephony0.1/copyright

            # qtdeclarative5-ubuntu-telephony-phonenumber0.1
            - usr/share/doc/qtdeclarative5-ubuntu-telephony-phonenumber0.1/copyright
            - usr/lib/*/qt5/qml/Ubuntu/Telephony/PhoneNumber/PhoneNumberField.qml
            - usr/lib/*/qt5/qml/Ubuntu/Telephony/PhoneNumber/libtelephonyservice-phonenumber-qml.so
            - usr/lib/*/qt5/qml/Ubuntu/Telephony/PhoneNumber/PhoneNumber.js
            - usr/lib/*/qt5/qml/Ubuntu/Telephony/PhoneNumber/PhoneNumberInput.qml
            - usr/lib/*/qt5/qml/Ubuntu/Telephony/PhoneNumber/qmldir
            - usr/lib/*/libphonenumber.so.7*

        after: [desktop-ubuntu-app-platform]

    environment:
        source: snap/
        plugin: dump
